### ISSUE TITLE
Design: Header sizes

### ISSUE THREAD

**Issue by maede97** [cevi/Cevi-Tools-Webpage#10]
The title "Online verfügbare Tools" is in markdown a H1, but the font-size is smaller than H2.
We could possibly:
- remove the h1 element and change the page title (or keep it for Webtools, but change it for "In Entwicklung"?
- change scss to make h1 bigger.

I like the first option better, what do you think?
![image](https://user-images.githubusercontent.com/14098502/146637309-cd2c5bb2-b770-463d-b5a2-d966de4b7a62.png)

**Comment by wp99cp** [comment]
Currently, both titles are h1 but with different CSS style properties. This is bad practice anyway and should be changed. When you look into the HTML template it gets lear that the first h1 (the bigger one) is the "page title", i.g. the entry from the navigation, the second h1 (the smaller one) gets rendered out of the Markdown file.

https://github.com/cevi/Cevi-Tools-Webpage/blob/5f6d6fa7ebc957e9d02050ae1bf607eba0ae2a9f/_layouts/page.html#L6-L12

Therefore a page, e.g.: 

```markdown
---
layout: page
title: In Entwicklung
permalink: /entwicklung/
weight: 2
---


# Webtools in Entwicklung
```

gets rendered as:
```HTML
<article class="post">

  <header class="post-header">
    <h1 class="post-title">In Entwicklung</h1>
  </header>

  <div class="post-content">
    <h1 id="webtools-in-entwicklung">Webtools in Entwicklung</h1>
<p>Hier zeigen wir euch bald, an welchen neuen spannenden Projekten wir arbeiten.</p>

  </div>

</article>
```

**Comment by wp99cp** [comment]
My suggestion, therefore, is to modify the HTML template such that the page title (same as nav entry) is omitted and only the Markdown title is rendered. Such an approach has the advantage, that the nav entry and the page title must not be identical.

**Comment by maede97** [comment]
I will create a PR that does this.

**Comment by maede97** [comment]
Well... this does not fix the issue.
The H1 title from the markdown file is smaller than the H2.
Maybe we keep the title from the site however remove the ones in the markdown files?

**Comment by wp99cp** [comment]
Just update the CSS as well. By copy past the style for the h1

https://github.com/cevi/Cevi-Tools-Webpage/blob/5f6d6fa7ebc957e9d02050ae1bf607eba0ae2a9f/_sass/minima/_layout.scss#L219-L227

into the section for rendering the markdown file

https://github.com/cevi/Cevi-Tools-Webpage/blob/5f6d6fa7ebc957e9d02050ae1bf607eba0ae2a9f/_sass/minima/_layout.scss#L229-L255

**Comment by wp99cp** [comment]
I still prefer separating page titles and navigation entries
