### ISSUE TITLE
Design: Project Entry layout

### ISSUE THREAD

**Issue by maede97** [cevi/Cevi-Tools-Webpage#12]
As of now, each project conists of the title, a short description and (at least) one image (claim / header).

We could potentially create an additional layout file for a single "project"? This way, every entry in the webpage would look the same.

**Comment by maede97** [comment]
Or why not simply use the posts feature, and setting categories and just show a list of posts for the respective category?

**Comment by wp99cp** [comment]
> Or why not simply use the posts feature, and setting categories and just show a list of posts for the respective category?

Sounds like an idea. But I would suggest separating "news posts" and posts of (new) tools. Maybe we can use "news posts" to announce new versions of the tools (e.g. of eMeal, CeviDB, ...). I have a script in mind that automatically makes a PR when for example the CeviDB version changes. But that's for the future... for now just keep in mind to don't mix those two things.
