### ISSUE TITLE
Link cevi.tools in Cevi Wiki

### ISSUE THREAD

**Issue by wp99cp** [cevi/Cevi-Tools-Webpage#16]
Add a link to [cevi.tools](cevi.tools) to the Cevi Wiki, probably on this page: https://wiki.cevi.ch/index.php/Technische_Hilfsmittel.

**Comment by ursforrer** [comment]
- [x] Added Cevi Tools to the side navigation of the cevi wiki
- [x] Added Section for Cevi Tools on the page  [Technische Hilfsmittel](https://wiki.cevi.ch/index.php/Technische_Hilfsmittel)
- [x] Added Qualitool to the list of tools
- [x] Added Automatic Walk Tables to the list of tools

Passt das? Oder habt ihr euch sogar noch einzelne Artikel zu den Tools vorgestellt?
