### ISSUE TITLE
Add existing applications of Cevi Dürnten as shareing for other "groups" (abteilungen)

### ISSUE THREAD

**Issue by ursforrer** [cevi/Cevi-Tools-Webpage#31]
Hoi zäme

Wir vom Cevi Dürnten haben über die Jahre hinweg eine ganzen Anwendungslandschaft aufgebaut um unsere Cevi "Prozesse".
Dazu gehören eine Mobile App, ein Webinterface, ein "Plugin" für die Webseite sowie eine API, welche all diese Sachen verbinden.

Dazu gehören folgende Features
- Abfrage vom Chästlizettel und der nächsten Daten auf dem Mobile
- An- und Abmeldung über die Mobile App
- Webinterface zum Eintragen der Chästlizettel Informationen sowie Einsicht über die An- und Abmeldungen
- Automatische Mails bei Eintragungen an die Eltern (über Mailverteiler der cevi.db)
- API zu Nextcloud zur Abfrage der Kalenderdaten.

[Link zum App Store](https://apps.apple.com/ch/app/cevi-dürnten/id1493348905)
[Link zum Webinterface](https://backend.ceviduernten.ch)
[Link zur API](https://api.ceviduernten.ch/swagger)
[Link zu den Repos](https://github.com/ceviduernten)

Das ganze Konstrukt kann grundsätzlich von jeder Abteilung wiederverwendet werden und so auch in ihrer Abteilung eingesetzt werden. Daher haben wir uns gedacht, könnte man dies vielleicht auch auf eurer "Homepage" teilen. 

Wäre dies in eurem Sinn? Oder eher nicht?
Falls ja, würde ich auch die Dokumentation zum Hosting und Co. etwas auf Vordermann bringen, dass dies für fast jeden verständlich wäre.

**Comment by wp99cp** [comment]
> Wäre dies in eurem Sinn? Oder eher nicht?

Finde ich eine sinnvolle Idee, ist ja auch eines unserer Ziele: Alle bestehenden Tools und Programme zu sammeln und auf der Webseite vorzustellen.

Evtl. macht es Sinn für diesen Zweck eine neue Kategorie (d.h. Seite) zu erstellen, z.B. "Tools für Abteilungen". Hierzu kannst du einfach einen PR machen und ein Markdown-File hinzufügen. Indem du in deinem Markdownfile folgende Linien hinzufügst, wird es von Jeykell erfasst und entsprechend eingepflegt:

https://github.com/cevi/Cevi-Tools-Webpage/blob/98f9975015213182d255d0388275d5b0762585ce/in-development.md?plain=1#L1-L6

**Comment by ursforrer** [comment]
Ok, danke euch. Sobald ich das mit den Push Berechtigungen hingebracht habe werde ich einen Pull Request erstellen. 👍
