### ISSUE TITLE
Titel "Tools für Abteilungen"

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/Cevi-Tools-Webpage#34]
Den Titel "Tools für Abteilungen" finde ich unpassend.
Denn auch der Logo-Generator, eMeal und der MZB-Generator sind Tools für Abteilungen.
Ausserdem haben wir uns bisher darauf beschränkt, bzw. die Premisse gehabt, dass Tools online und "ready to use" sein sollten.
Dies trifft auf die dort vorgestellte API / App / Chästlizettel nicht zu.

**Comment by wp99cp** [comment]
Ich gebe dir Recht, dass der Titel "Tools für Abteilung" vielleicht nicht Ideal ist. Ich finde aber trotzdem, dass wir eine Sektion für "Abteilungs-Interne Tools" haben sollen. Schliesslich, so finde ich, ist eine wichtige Aufgabe von Cevi.Tools die Sammlung bestehender Tools und Software-Möglichkeiten rund um den Cevi. Auch solche die nicht fertig bzw. nicht direkt via Webinterface zugänglich sind. Cevi.Tools soll in meinen Augen als zentrales Register für alle spannenden Projekte dienen.

Ich würde daher folgenden Vorschlagen: Wir suchen einen besseren Titel für die entsprechende Unterseite, lassen die Dürntner-Tools aber bestehen und ergänzen die Seite mit weiteren solchen Projekten. Ich habe in meiner Abteilung auch noch einige solch kleinere "Tools", die ich beispielsweise dort verlinken könnt.

Als Titel schlage ich etwas wie folgt vor: in der Navigation: "Abteilungs-Interne Tools" und dann auf der Seite: "Software-Projekte aus den Abteilungen: Tools, die du in deiner Abteilung selber aufsetzen kannst"

**Comment by ThomasHaefliger** [comment]
Ich schlage vor, die Navigation nicht weiter aufzublasen.
Wer Tools nutzen will, die selber noch Anpassung / Programmierung benötigen, wird sich wohl auch mit Github zurecht finden.
Daher ist mein Vorschlag, im Cevi Repo eine Linkliste anzulegen und auf der cevi.tools Website einfach darauf zu verweisen
