### ISSUE TITLE
Dependabot not working properly

### ISSUE THREAD

**Issue by patrickuhlmann** [cevi/Cevi-Tools-Webpage#50]
It fails with
`Run FirebaseExtended/action-hosting-deploy@v0
/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:2102
        throw new Error(`Input required and not supplied: ${name}`);
        ^`

The reason can be found in the documentation (https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions):
`When a Dependabot event triggers a workflow, the only secrets available to the workflow are Dependabot secrets. GitHub Actions secrets are not available. Consequently, you must store any secrets that are used by a workflow triggered by Dependabot events as Dependabot secrets. `

This affects the following two secrets:
- GITHUB_TOKEN
- CEVI_TOOLS_FIREBASE_PREVIEW_TOKEN

They can be added under Settings/Secrets and variables/Dependabot. If we use the same names it should then work. But unfortunately I don't have permission to do so.

@wp99cp can you please do this?

**Comment by maede97** [comment]
GITHUB_TOKEN is not set there. I think that it is given by github automatically?
The other token I could set, but I don't know the value :-)

**Comment by patrickuhlmann** [comment]
I also don't know the value. I guess only @wp99cp knows it :D

**Comment by wp99cp** [comment]
I've added the missing secret, dependency bot builds should now work as expected
