### ISSUE TITLE
Incorporate KuTo

### ISSUE THREAD

**Issue by maede97** [cevi/Cevi-Tools-Webpage#9]
Incorporate the other repository KuTo (Kurs-Tools) into this repo as well.

**Comment by ThomasHaefliger** [comment]
Will do. To be sure, so far it's only Gruppeneinteilung?

**Comment by maede97** [comment]
If you want, you can do it as well. I can also do it myself. :-)

**Comment by maede97** [comment]
Yes, it's only Gruppeneinteilung
